security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        # App\Entity\Admin:
        #     algorithm: bcrypt
        #     cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # app_user_provider:
        #     entity:
        #         class: App\Entity\Admin
        #         property: username
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # guard:
            #     authenticators:
                    # - App\Security\AdminFormAuthenticator

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }