security:
    encoders:
        App\Entity\MembersOfBasketCompouned:
            algorithm: bcrypt
        App\Entity\MembersOfBasketCollected:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    providers:
        in_memory: { memory: ~ }
        chain_provider:
            chain:
                providers: [in_database_members_of_basket_compouned, in_database_members_of_basket_collected]
        in_database_members_of_basket_compouned:
            entity: { class: App\Entity\MembersOfBasketCompouned, property: email}
        in_database_members_of_basket_collected:
            entity: { class: App\Entity\MembersOfBasketCollected, property: email}
                
                
        in_database_admin:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        visitor:
            pattern: ^/(presentation|inscriptionBaskColl|inscriptionBaskComp)
            anonymous: true
        members:
            pattern: ^/(connexionMembres|deconnexionMembres|members)
            anonymous: true

            provider: chain_provider

            form_login:
                login_path: security_login_members
                check_path: security_login_members
                default_target_path: my_compte

            logout:
                path: security_deconnect_member
                target: visitor_home

        admin:
            pattern: ^/(connexionAdmin|deconnexionAdmin|admin)
            anonymous: true

            provider: in_database_admin

            form_login:
                login_path: security_login_admin
                check_path: security_login_admin
                default_target_path: home_admin

            logout:
                path: security_deconnect_admin
                target: visitor_home

        main: 
            pattern: ^/
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/member, roles: ROLE_USER }