security:
    encoders:
        App\Entity\Members:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    providers:
        in_memory: { memory: ~ }
        in_database_members:
            entity:
                class: App\Entity\Members
                property: email
        in_database_admin:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        visitor:
            pattern: ^/(home|presentation|inscriptionBaskColl|inscriptionBaskComp)
            anonymous: true
        members:
            pattern:  ^/(connexionMembres|deconnexionMembres|members)
            anonymous: true

            provider: in_database_members

            form_login:
                login_path: security_login_members
                check_path: security_login_members
                default_target_path: my_compte

            logout: 
                path: security_deconnect_member
                target: visitor_home

        admin:
            pattern:  ^/(connexionAdmin|deconnexionAdmin|admin)
            anonymous: true

            provider: in_database_admin

            form_login: 
                login_path: security_login_admin
                check_path: security_login_admin
                default_target_path: home_admin

            logout:
                path: security_deconnect_admin
                target: visitor_home
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }