security:
    encoders:
        App\Entity\Members:
            algorithm: bcrypt

    providers:
        in_memory: { memory: ~ }
        in_database_members:
            entity:
                class: App\Entity\Members
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: in_database_members

            form_login:
                login_path: security_login_members
                check_path: security_login_members

            logout: 
                path: security_deconnect_member
                target: visitor_home
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }